CREATE TABLE product
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    price           DOUBLE PRECISION,
    stock_balance   INTEGER,
    reserve_balance INTEGER,
    CONSTRAINT pk_product PRIMARY KEY (id)
);
